platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

target 'Source_Example' do
  pod 'Source', :path => '../'

  target 'Source_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end