name: CI
on: [push, pull_request]
env:
  FASTLANE_XCODE_LIST_TIMEOUT: 999
  FASTLANE_WORK_DIR: .
  MINT_PATH: ${{ github.workspace }}/mint

jobs:
  bootstrap-and-test:
    name: Test
    runs-on: macOS-latest
    steps:      
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cache RubyGems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gem-
      - name: Cache Mint packages
        uses: actions/cache@v1
        with:
          path: ${{ env.MINT_PATH }}
          key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
          restore-keys: ${{ runner.os }}-mint-
      - name: Install dependencies
        run: sh ./bootstrap.sh
      - name: Run tests
        run: bundle exec fastlane test framework:"Source"
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}